name =  input("What is your name?\n")
names_file = open("names.txt", "w")
names_file.write(name)
names_file.close()
names_file = open("names.txt", "r")
print(f"Your name is {names_file.read()}")
names_file.close()
sum_of_lines = 0
numbers_file = open("numbers.txt", "r")
lines_to_read = int("2")
for i in range(0, lines_to_read, 1):
    sum_of_lines += int(numbers_file.readline())
print(sum_of_lines)
numbers_file.close()
numbers_file = open("numbers.txt", "r")
list_of_all_lines = map(int, numbers_file)
sum_of_all_lines = sum(list_of_all_lines)
print(sum_of_all_lines)
numbers_file.close()
exit()